name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          uname -a
          cmake --version
          g++ --version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libdrogon-dev
          sudo apt install -y libjsoncpp-dev
          sudo apt install -y uuid-dev
          sudo apt install -y libmysqlclient-dev
          sudo apt install -y libyaml-cpp-dev

      - name: Patch DrogonConfig
        run: |
          sudo sed -i '/find_dependency(MySQL)/s/^/#/' \
            /usr/lib/x86_64-linux-gnu/cmake/Drogon/DrogonConfig.cmake

          sudo sed -i '/find_dependency(Hiredis)/s/^/#/' \
            /usr/lib/x86_64-linux-gnu/cmake/Drogon/DrogonConfig.cmake

          sudo sed -i '/find_dependency(Brotli)/s/^/#/' \
            /usr/lib/x86_64-linux-gnu/cmake/Drogon/DrogonConfig.cmake

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Understand app folder structure
        run: |
          find /home/runner/work/ -name "*" -print
          ls -l /home/runner/
          echo "-1-"
          ls -l /home/runner/work/
          echo "-2-"
          ls -l /home/runner/work/payment_app
          echo "-3-"
          cd /home/runner/work/payment_app
          echo "-4-"
          ls -lrt
          echo "-5-"
          pwd
          echo "-6-"
          

      - name: Run tests
        run: |
          ./build/test/payment_app_test

