name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          uname -a
          cmake --version
          g++ --version

      - name: Install dependencies
        run: |
          sudo apt update

      - name: Show CMake packages
        run: |
          find /usr -name DrogonConfig.cmake 2>/dev/null

      - name: Configure
        run: |
         cmake -B build
         cmake --build build

