name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          uname -a
          cmake --version
          g++ --version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libdrogon-dev
          sudo apt install -y libjsoncpp-dev
          sudo apt install -y uuid-dev
          sudo apt install -y libmysqlclient-dev
          sudo apt install -y libyaml-cpp-dev

      - name: Patch DrogonConfig
        run: |
          sudo sed -i '/find_dependency(MySQL)/s/^/#/' \
            /usr/lib/x86_64-linux-gnu/cmake/Drogon/DrogonConfig.cmake

          sudo sed -i '/find_dependency(Hiredis)/s/^/#/' \
            /usr/lib/x86_64-linux-gnu/cmake/Drogon/DrogonConfig.cmake

          sudo sed -i '/find_dependency(Brotli)/s/^/#/' \
            /usr/lib/x86_64-linux-gnu/cmake/Drogon/DrogonConfig.cmake

      - name: Configure
        run: |
          pwd
          cmake -B build

      - name: Build
        run: |
          pwd
          cmake --build build

      - name: Run tests
        env:
            PAYMENT_APP_CONFIG: ${{ github.workspace}}/config/appsettings.json
            PAYMENT_APP_LOG: ${{github.workspace}}/log/payment_app.log
        run: |
          pwd
          cd build/test
          ./payment_app_test

